services:
  local-mysql-aa:
    image: mysql
    container_name: techup-mysql-aa
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    platform: linux/amd64

  local-redis-aa:
    image: redis
    container_name: techup-redis-aa
    ports:
      - "6378:6379"
    platform: linux/amd64