spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
  config:
    import: classpath:application-integration.yml

logstash:
  host: ${logstashhost:localhost}
  port: ${logstashport:9601}


slack:
  bot-token: ${slack.token}
  log-channel: ${slack.channel}

server:
  port: 8080

ratelimit:
  enabled: true