spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.scheme}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    show-sql: false
  data:
    redis:
      ssl:
        enabled: true
      cluster:
        nodes: ${redis.host}
        max-redirects: 3
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}

jwt:
  secret: ${kt.jwt.secret}
  access-token-expiration: ${kt.jwt.access-token-expiration}
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration}

slack:
  bot-token: ${slack.token}
  log-channel: ${slack.channel}

server:
  port: ${server.port}